<a href="https://colab.research.google.com/github/vimmiseth/StockAnalysis/blob/main/Copy_of_Finance_101_Portfolio_Assets_Allocation_and_Statistical_Data_Analysis_Skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TASK #1: PROJECT OVERVIEW AND ASSET TYPES

![alt text](https://drive.google.com/uc?id=1TEVVCFWQD8F5mlC7FzD-JM2y54ivYZHT)

![alt text](https://drive.google.com/uc?id=1Z253Wmij7HCEHqPsMdEI56qYqASRrsjn)


![alt text](https://drive.google.com/uc?id=10XxwtKY2qEiNAdTkqNXKhNFZrWvwwKbN)

![alt text](https://drive.google.com/uc?id=1SfBtfOoDigo4ofEvPAwIojqGHpMojL5S)

Links:
- https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/
- https://ca.finance.yahoo.com/quote/AAPL?p=AAPL&.tsrc=fin-tre-srch
- https://investor.vanguard.com/etf/profile/performance/voo
- https://grow.acorns.com/warren-buffett-index-funds/



# TASK #2: IMPORT LIBRARIES & DATASETS AND PERFORM DATA VISUALIZATION

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import plotly.express as px
from copy import copy
from scipy import stats
import matplotlib.pyplot as plt
import numpy as np
import plotly.figure_factory as ff
import plotly.graph_objects as go

In [ ]:
# Read the stock data file
dfStocks = pd.read_csv('/content/drive/My Drive/Colab Notebooks/stocks.csv')
dfStocks.head(2)

Date       AAPL         BA  ...       TSLA        GOOG        sp500
0  2012-01-12  60.198570  75.510002  ...  28.250000  313.644379  1295.500000
1  2012-01-13  59.972858  74.599998  ...  22.790001  311.328064  1289.089966

[2 rows x 10 columns]

In [ ]:
# Sort the data based on Date


**MINI CHALLENGE #1:** 
- **Use Plotly express to visualize raw stock data and normalized ones** 

# TASK #3: UNERSTAND THE CONCEPT OF ASSET ALLOCATION

![alt text](https://drive.google.com/uc?id=17SLLaxLeP6vlXH6MltEQMFNbt5u-J6iK)

![alt text](https://drive.google.com/uc?id=1qLML-ejBIKR8Bv8aeItfNaJuhq5GzvJ5)

![alt text](https://drive.google.com/uc?id=1iR3WYvU9SYVRqhKwR91x0AsE5sGQtFhz)

**MINI CHALLENGE #2:**
- **What is the common advice that financial advisors generally give to retired seniors when it comes to asset allocations?**

# TASK #4: PERFORM RANDOM ASSET ALLOCATION AND CALCULATE PORTFOLIO DAILY RETURN

In [ ]:
np.random.seed(101)
ar = np.array(np.random.random(9))
ar

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686, 0.30696622, 0.89361308, 0.72154386])

In [ ]:
arn = ar/np.sum(ar)
arn

array([0.10921307, 0.12069041, 0.00602201, 0.03627509, 0.14492913,
       0.17636073, 0.06492024, 0.1889901 , 0.15259921])

In [ ]:
arn1 = np.round_(arn,6)
arn1

array([0.109213, 0.12069 , 0.006022, 0.036275, 0.144929, 0.176361,
       0.06492 , 0.18899 , 0.152599])

In [ ]:
# Normalize the stock avalues 
dfnstocks = normalize(dfStocks)
dfnstocks.head(2)

Date      AAPL        BA  ...      TSLA      GOOG     sp500
0  2012-01-12  1.000000  1.000000  ...  1.000000  1.000000  1.000000
1  2012-01-13  0.996251  0.987949  ...  0.806726  0.992615  0.995052

[2 rows x 10 columns]

In [ ]:
for counter, stock in enumerate(dfnstocks.columns[1:]):
  dfnstocks[stock] = dfnstocks[stock]*arn1[counter]*1000000
dfnstocks.head(2)

Date           AAPL  ...           GOOG          sp500
0  2012-01-12  109213.000000  ...  188990.000000  152599.000000
1  2012-01-13  108803.510461  ...  187594.277962  151843.951927

[2 rows x 10 columns]

Date           AAPL  ...          sp500  Daily Worth
0  2012-01-12  109213.000000  ...  152599.000000            1
1  2012-01-13  108803.510461  ...  151843.951927            1

[2 rows x 11 columns]

In [ ]:
x = dfnstocks.drop(columns = ['Date'])
dfnstocks['Daily Worth'] = x.sum(axis = 1)
dfnstocks.head(2)

Date           AAPL  ...          sp500    Daily Worth
0  2012-01-12  109213.000000  ...  152599.000000  999999.000000
1  2012-01-13  108803.510461  ...  151843.951927  984778.289084

[2 rows x 11 columns]

In [ ]:
dfnstocks['Daily Worth in %'] = 0.0000
for i in range(1, len(dfnstocks)):
  dfnstocks['Daily Worth in %'][i] = (dfnstocks['Daily Worth'][i] - dfnstocks['Daily Worth'][i-1])/dfnstocks['Daily Worth'][i-1]
dfnstocks.head(2)

Date           AAPL  ...    Daily Worth  Daily Worth in %
0  2012-01-12  109213.000000  ...  999999.000000          0.000000
1  2012-01-13  108803.510461  ...  984778.289084         -0.015221

[2 rows x 12 columns]

In [ ]:
# Note that enumerate returns the value and a counter as well



In [ ]:
# Let's create an additional column that contains the sum of all $ values in the portfolio


In [ ]:
# Let's calculate the portfolio daily return 
# Define a new column in the dataframe and set it to zeros




**MINI CHALLENGE #3:** 
- **Try at least 3 another random weights allocation and rerun the code.** 
- **Compare the final portfolio value on Aug 11th, 2020 to its initial value ($1M) on January 12th, 2012. Do you notice a big difference? Comment on your answer.**

# TASK #5: PORTFOLIO ALLOCATION - DAILY RETURN/WORTH CALCULATION (FUNCTION)

In [149]:
# Lets assume we have $1,000,000 to be invested and we will allocate this fund based on the weights of the stocks
# We will create a function that takes in the stock prices along with the weights and return:
# (1) Daily value of each individual securuty in $ over the specified time period
# (2) Overall daily worth of the entire portfolio 
# (3) Daily return 

def portfolio_alloc(df, ar1):
  dfnstocks = normalize(df)
  

  for counter, stock in enumerate(dfnstocks.columns[1:]):
    dfnstocks[stock] = (dfnstocks[stock]*ar1[counter])*1000000
    
  x = dfnstocks.drop(columns = ['Date'])
  dfnstocks['Daily Worth'] = x.sum(axis = 1)
  

  dfnstocks['Daily Worth in %'] = 0.0000
  for i in range(1, len(dfnstocks)):
    dfnstocks['Daily Worth in %'][i] = (dfnstocks['Daily Worth'][i] - dfnstocks['Daily Worth'][i-1])/dfnstocks['Daily Worth'][i-1]
  dfnstocks['Daily Worth in %'][0] = 0.0000

  return dfnstocks


np.random.seed(101)
ar = np.array(np.random.random(9))
arn = ar/np.sum(ar)
arn1 = np.round_(arn,6)
arn1

df_portfolio = portfolio_alloc(dfStocks, arn1)
df_portfolio.head(2)


Date           AAPL  ...    Daily Worth  Daily Worth in %
0  2012-01-12  109213.000000  ...  999999.000000          0.000000
1  2012-01-13  108803.510461  ...  984778.289084         -0.015221

[2 rows x 12 columns]

**MINI CHALLENGE #4:**
- **Call the function and ensure that the results make sense**

# TASK #6: PERFORM PORTFOLIO DATA VISUALIZATION

In [ ]:
# Plot the portfolio daily return


In [ ]:
# Plot all stocks (normalized)



In [ ]:
# Print out a histogram of daily returns


**MINI CHALLENGE #5:** 
- **Plot the portfolio overall daily worth vs. time.**
- **Rerun the code with various weights and visualize the final value.** 

In [150]:
fig = px.line(x= df_portfolio['Date'], y= df_portfolio['Daily Worth'] , title="portfolio overall daily worth vs. time")
fig.show()

# TASK #7: UNDERSTAND PORTFOLIO STATISTICAL METRICS (CUMMULATIVE RETURN, AVERAGE DAILY RETURN, AND SHARPE RATIO)

![alt text](https://drive.google.com/uc?id=1W_MNP2Qldn3ulrvXivOnjQg3NTf3hNCo)

![alt text](https://drive.google.com/uc?id=12e4Zgxv1FNviJYML88G6cTnlte0bts-4)

![alt text](https://drive.google.com/uc?id=1QQLWpIJ8uXopJrV40YFKb5H-SxnmsRaj)

# TASK #8: CALCULATE PORTFOLIO STATISTICAL METRICS (CUMMULATIVE RETURN, AVERAGE DAILY RETURN, AND SHARPE RATIO)

In [169]:
# Cummulative return of the portfolio (Note that we now look for the last net worth of the portfolio compared to it's start value)


print(df_portfolio.head(2))
print(df_portfolio.tail(2))


print('df_portfolio[-1:]: {}'.format(df_portfolio['Daily Worth'][-1:]) )
#print('df_portfolio[0]: {}'.format(df_portfolio['Daily Worth'][0]) )
#print('df_portfolio[ {}'.format( ((df_portfolio['Daily Worth'][-1:] - df_portfolio['Daily Worth'][0])/df_portfolio['Daily Worth'][0])) )
Cummulative_return  =  ((df_portfolio['Daily Worth'][-1:] - df_portfolio['Daily Worth'][0])/df_portfolio['Daily Worth'][0])*100
print('Cummulative_return: {}'.format(Cummulative_return.values[0]) )

         Date           AAPL  ...    Daily Worth  Daily Worth in %
0  2012-01-12  109213.000000  ...  999999.000000          0.000000
1  2012-01-13  108803.510461  ...  984778.289084         -0.015221

[2 rows x 12 columns]
            Date           AAPL  ...   Daily Worth  Daily Worth in %
2157  2020-08-10  818046.579293  ...  8.450439e+06         -0.006537
2158  2020-08-11  793717.982005  ...  8.256673e+06         -0.022930

[2 rows x 12 columns]
df_portfolio[-1:]: 2158    8.256673e+06
Name: Daily Worth, dtype: float64
Cummulative_return: 725.6681204606973


In [170]:
# Calculate the portfolio standard deviation
print('Cummulative_return: {}'.format(df_portfolio['Daily Worth in %'].std()) )

Cummulative_return: 0.014491475546693404


In [171]:
# Calculate the average daily return 
print('Cummulative_return: {}'.format(df_portfolio['Daily Worth in %'].mean()) )

Cummulative_return: 0.0010836651112905507


In [ ]:
# Portfolio sharpe ratio


**MINI CHALLENGE #6:** 
- **Try at least 3 different random weights allocation, rerun the code and compare sharpe ratios, daily return and cummulative returns.**

In [172]:
sharp_ratio = df_portfolio['Daily Worth in %'].mean()/ df_portfolio['Daily Worth in %'].std()*np.sqrt(252)
print('sharp_ratio: {}'.format(sharp_ratio))

sharp_ratio: 1.1870875590468632


# **WELL DONE!**

# **MINI CHALLENGE SOLUTIONS**

**MINI CHALLENGE #1 SOLUTION:** 
- **Use Plotly express to visualize raw stock data and normalized ones** 

In [ ]:
# Function to normalize the prices based on the initial price
def normalize(df):
  x = df.copy()
  for i in x.columns[1:]:
    x[i] = x[i]/x[i][0]
  return x

In [ ]:
# Function to plot interactive plot
def interactive_plot(df, title):
  fig = px.line(title = title)
  for i in df.columns[1:]:
    fig.add_scatter(x = df['Date'], y = df[i], name = i)
  fig.show()

In [ ]:
# Plot interactive chart
interactive_plot(stocks_df, 'Prices')

NameError: ignored

In [ ]:
# Plot normalized interactive chart
interactive_plot(normalize(stocks_df), 'Normalized Prices')

**MINI CHALLENGE #2 SOLUTION:**
- **What is the common advice that financial advisors generally recommend to retired seniors when it comes to asset allocations?**

In [ ]:
# The conventional wisdom is to subtract client's age from 100 to calculate the % of portolio that should be allocated to stocks
# For Example: If you're 30 years old, you should have 70% allocated to stocks
# If you are 75 years old, you should invest 25% in stocks (old retired seniors generally recommend a more stable low risk portfolio). 

**MINI CHALLENGE #3 SOLUTION:** 
- **Try at least 3 another random weights allocation and rerun the code.** 
- **Compare the final portfolio value on Aug 11th, 2020 to its initial value ($1M) on January 12th, 2012. Do you notice a big difference? Comment on your answer.**

In [ ]:
# remove the seed value of 101, run the code 3 times, and record the final portolio value on the last day (Aug 11th, 2020)
np.random.seed()

# Portfolio Value Run #1 = $6.383645e+06, weights = [0.01246531 0.23749173 0.18257962 0.03419922 0.08369018 0.23405306
 0.07120053 0.00824087 0.13607948]

# Portfolio Value Run #2 = $9.594104e+06, Weights = [0.13932903 0.04729773 0.15580758 0.03232255 0.0629491  0.15081605
 0.12206726 0.16938746 0.12002324]

# Portfolio Value Run #3 = 1.138105e+07, Weights = [0.17707261 0.06977804 0.02394314 0.1550952  0.11152213 0.12017452
 0.14296447 0.05729485 0.14215505]

**MINI CHALLENGE #4 SOLUTION:**
- **Call the function and ensure that the results make sense**

In [ ]:
# Call the function
df_portfolio = portfolio_allocation(stocks_df, weights)
df_portfolio

**MINI CHALLENGE #5 SOLUTION:** 
- **Plot the portfolio overall daily worth vs. time.**
- **Rerun the code with various weights and visualize the final value.** 

In [ ]:
fig = px.line(x = df_portfolio.Date, y = df_portfolio['portfolio daily worth in $'], title= 'Portfolio Overall Value in $')
fig.show()

**MINI CHALLENGE #6 SOLUTION:** 
- **Try at least 3 different random weights allocation, rerun the code and compare sharpe ratios, daily return and cummulative returns.**

In [ ]:
# Rerun the code with 3 random values and compare metrics